services:
  - docker

matrix:
  include:
    - language: java
      jdk: openjdk12
      script: ./.build-java

    - language: node_js
      node_js:
        - "14"
      script: ./.build-node
  
    - language: python
      python:
        - "3.8"
      script: ./.build-python
